name: Checks

on:
  push:
    branches:
      - main
  pull_request: {}
  schedule:
    - cron: '0 23 * * SUN-THU'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    if: (github.event_name == 'schedule' && github.repository == 'iwiwi/epochraft-hf-fsdp') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install
      run: |
        python -m pip install -U pip
        pip install --progress-bar off -U .[development]

    - name: Output installed packages
      run: |
        pip freeze --all

    - name: Output dependency tree
      run: |
        pip install pipdeptree
        pipdeptree

    - name: black
      run: black . --check --diff

    - name: flake8
      run: flake8 .

    - name: isort
      run: isort . --check --diff

    - name: mypy
      run: mypy .

    - name: blackdoc
      run: blackdoc . --check --diff
